### ISSUE TITLE
PHP 5.3

### ISSUE THREAD

**Issue by GoktugOzturk** [logical-and/php-oauth#43]
can we reduce the dependency for this repo to 5.3?
both lusitanian/oauth and oryzone/oauth-user-data requires 5.3

PHP 5.3 is used by 40.9% of all the websites.
http://w3techs.com/technologies/details/pl-php/5/all

I saw some short array syntax. Other than that is there any reason not to downgrade requirement to 5.3 ?

**Comment by OzzyCzech** [comment]
+1

**Comment by vuthao** [comment]
+1

**Comment by smazurov** [comment]
:-1: 
w3techs is a terrible source of this type of information (how is 5.7 even on the chart?). [This](http://seld.be/notes/my-view-of-php-version-adoption) is a much better view, where in Nov of last year 5.3 was at 14.85%. I would be surprised if it passes 10% this year. Upgrade your app to 5.6 and don't drag the rest of the ecosystem down, especially since you have a perfectly valid alternative.
